version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'echo "text to output here" > output.txt'
  print_output_file:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: output
          command: 'echo "reademme" > file.txt'


workflows:
  version: 2
  my_flow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: 
            - save_hello_world_output