version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - save_hello_world_output

jobs:
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'echo "text to output here" > output.txt'
  print_output_file:
