version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: /tmp

jobs:
  save_hello_world_output:
    executor: my-executor
    steps:
      - run: mkdir -p workspace
      - run: 'echo "text to output here" > output.txt'

       - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: workspace
          # Must be relative path from root
          paths:
            - echo-output

  print_output_file:
    executor: my-executor
    steps:
    - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace

      - checkout:
      - run:
          name: output
          command: 'echo "reademme" > file.txt'


workflows:
  version: 2
  my_flow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: 
            - save_hello_world_output